# Perfil "memoria": desarrollo/pruebas SIN conexion a la base de datos real.
#
# Le decimos a Spring Boot que NO intente auto-configurar un DataSource ni JPA,
# porque si no, la aplicacion falla al arrancar buscando una BD que no existe
# en este perfil (aunque UsuarioRepositorioJpaAdapter este desactivado, Spring
# Boot igual intentaria crear la conexion por el starter de JPA).
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration,org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration
